# 流水线名
name: 模拟PR检查失败流水线

#触发方式
on:
  # pull_request触发
  pull_request:
    # 监听分支
    branches:
      - master
      
# 执行步骤
jobs:
  checkCode:
    name: 检查代码
    # 执行环境
    runs-on: ubuntu-latest
    # 执行步骤
    steps:
      - name: 模拟报错
        run: |
          exit 100
